version: '3.6'

services:
  db:
    image: postgres:10.7-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  migration:
    build: .
    env_file:
    - .env
    command: python /app/manage.py migrate
    depends_on:
      - db
  web:
    build: .
    env_file:
    - .env
    ports:
      - 8000:8000
    command: python /app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - migration

volumes:
  postgres_data: