# Generated by Django 2.1.7 on 2019-03-03 04:59

import atlas.apps.account.managers
import atlas.apps.account.utils
import atlas.common.core.validators
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', sep='', slugify=atlas.apps.account.utils.slugify_username, unique=True)),
                ('ui_sso_username', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='SSO UI username')),
                ('ui_sso_npm', models.CharField(blank=True, max_length=16, null=True, verbose_name='SSO UI NPM')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', atlas.apps.account.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[atlas.common.core.validators.PhoneRegex()])),
                ('birthplace', models.CharField(max_length=128)),
                ('birthdate', models.DateField(null=True)),
                ('residence_city', models.CharField(blank=True, max_length=128, null=True)),
                ('residence_country', models.CharField(blank=True, max_length=128, null=True)),
                ('latest_csui_generation', models.SmallIntegerField(blank=True, null=True, verbose_name='Angkatan')),
                ('latest_csui_graduation_status', models.CharField(blank=True, choices=[('TL', 'Tidak Lulus'), ('BL', 'Belum Lulus'), ('SL', 'Sudah Lulus')], max_length=1, null=True, verbose_name='Kelulusan')),
                ('profile_pic_url', models.URLField(blank=True, null=True, verbose_name='Profile Picture')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
