# Generated by Django 2.1.7 on 2019-03-05 10:39

import atlas.apps.account.utils
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('should_send_newsletter', models.BooleanField(default=True, help_text='Designates that if this is active, then user should receive email about Newsletter.', verbose_name='Send Newsletter')),
                ('should_send_event', models.BooleanField(default=True, help_text='Designates that if this is active, then user should receive email about Event update.', verbose_name='Send Event Update')),
                ('should_send_vacancy', models.BooleanField(default=True, help_text='Designates that if this is active, then user should receive email about Vacancy update.', verbose_name='Send Vacancy Update')),
                ('should_send_donation_info', models.BooleanField(default=True, help_text='Designates that if this is active, then user should receive email about Donation information.', verbose_name='Send Donation Information')),
                ('should_send_update', models.BooleanField(default=True, help_text='Designates that if this is active, then user should receive email about General update.', verbose_name='Send General Update')),
                ('could_contact_me', models.BooleanField(default=False, help_text='Designates that if this is active, then we could contact user as Fasilkom UI about matter.', verbose_name='Contact the person, personally')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', sep='', slugify=atlas.apps.account.utils.slugify_username, unique=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
