# Generated by Django 2.1.7 on 2019-03-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='latest_csui_generation',
            new_name='latest_csui_class',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthplace',
        ),
    ]
