# Generated by Django 2.1.7 on 2019-03-17 05:01

import atlas.apps.account.utils
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text="Designates that if this user email is not verified,then can't access other services except Account Service", verbose_name='Email Verified status'),
        ),
        migrations.AddField(
            model_name='user',
            name='preference',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=atlas.apps.account.utils.default_preference, help_text='Here is the user preference, we can add some later', verbose_name='User Preference'),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
