# Generated by Django 2.1.7 on 2019-04-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190323_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='latest_csui_program',
            field=models.CharField(blank=True, choices=[('S1-IK', 'S1 - Ilmu Komputer'), ('S1_KI-IK', 'S1 KI - Ilmu Komputer'), ('S1-SI', 'S1 - Sistem Informasi'), ('S1_EKS-SI', 'S1 Ekstensi - Sistem Informasi'), ('S2-MIK', 'S2 - Magister Ilmu Komputer'), ('S2-MTI', 'S2 - Magister Teknologi Informasi'), ('S3-IK', 'S3 - Doktor Ilmu Komputer')], max_length=10, verbose_name='Prodi'),
        ),
    ]
