# Generated by Django 2.1.7 on 2019-04-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190401_1416'),
        ('account', '0008_auto_20190331_0052'),
    ]

    operations = [
    ]
