# Generated by Django 2.1.7 on 2019-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_merge_20190405_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ui_sso_npm',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='SSO UI NPM'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latest_csui_program',
            field=models.CharField(blank=True, choices=[('S1-IK', 'S1 - Ilmu Komputer'), ('S1_KI-IK', 'S1 KI - Ilmu Komputer'), ('S1-SI', 'S1 - Sistem Informasi'), ('S1_EKS-SI', 'S1 Ekstensi - Sistem Informasi'), ('S2-IK', 'S2 - Ilmu Komputer'), ('S2-TI', 'S2 - Teknologi Informasi'), ('S3-IK', 'S3 - Ilmu Komputer')], max_length=10, verbose_name='Prodi'),
        ),
    ]
