# Generated by Django 2.1.7 on 2019-04-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190415_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Menentukan apakah pengguna memiliki semua hak akses tanpa perlu diberikan secara manual.', verbose_name='Superuser status'),
        ),
    ]
