# Generated by Django 2.1.7 on 2019-05-07 04:09

import atlas.libs.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20190422_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ui_sso_username',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='ui_sso_npm',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, validators=[atlas.libs.core.validators.NumericRegex()], verbose_name='SSO UI NPM'),
        ),
    ]
