# Generated by Django 2.1.7 on 2019-05-16 15:02

import atlas.apps.account.utils
import atlas.libs.core.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20190516_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Menentukan bahwa jika pengguna ini tidak aktif, maka tidak dapat masuk.', verbose_name='Status aktif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Menunjukkan bahwa jika email pengguna ini tidak diverifikasi, maka tidak dapat mengakses layanan lain kecuali Layanan Akun', verbose_name='Status verifikasi email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Menunjukkan bahwa pengguna ini dapat masuk ke situs administrator.', verbose_name='Status staf'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Menunjukkan bahwa pengguna ini memiliki semua izin tanpa menetapkan secara eksplisit.', verbose_name='Status superuser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Menunjukkan bahwa jika pengguna ini tidak diverifikasi, maka tidak dapat mengakses layanan lain kecuali Layanan Akun', verbose_name='Status verifikasi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=atlas.apps.account.utils.default_preference, help_text='Di sini adalah preferensi pengguna, kita dapat menambahkan beberapa nanti', verbose_name='Preferensi Pengguna'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ui_sso_npm',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, validators=[atlas.libs.core.validators.NumericRegex()], verbose_name='NPM SSO UI'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.URLField(blank=True, default='https://s3-ap-southeast-1.amazonaws.com/b3-mnemosyne-dev/img/default-profile-pic.jpeg', verbose_name='Foto Profil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='residence_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Lintang Tempat Tinggal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='residence_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Bujur Tempat Tinggal'),
        ),
    ]
