# Generated by Django 2.1.7 on 2020-01-07 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200104_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid linkedin URL (example: https://linkedin.com/in/<username>', regex='https?:\\/\\/(www\\.)?linkedin\\.com\\/in\\/(\\w+)')], verbose_name='Linkedin URL'),
        ),
    ]
