# Generated by Django 2.1.7 on 2022-04-14 15:40

import atlas.apps.account.utils
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20200121_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='top_skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=atlas.apps.account.utils.default_top_skills, help_text='Here is the top skills, we can add some later', verbose_name='Top Skills'),
        ),
    ]
