# Generated by Django 2.1.7 on 2022-05-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_add_field_top_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_from_sisidang',
            field=models.BooleanField(default=False, verbose_name='From Sisidang'),
        ),
    ]
