# Generated by Django 2.1.7 on 2022-06-07 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_add_is_from_sisidang_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid linkedin URL (example: https://linkedin.com/in/<username>', regex='https?:\\/\\/(www\\.)?(id\\.)?linkedin\\.com\\/in\\/(\\w+)')], verbose_name='Linkedin URL'),
        ),
    ]
