# Generated by Django 2.1.7 on 2023-03-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0004_auto_20230309_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='tanggal_dikirim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
