# Generated by Django 2.1.7 on 2023-03-09 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survei', '0005_auto_20230309_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='survei',
            name='creator',
            field=models.ForeignKey(default='c502aff3-bf58-48cd-b034-02da4f1ee16d', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
