# Generated by Django 2.1.15 on 2023-05-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0007_pertanyaan_jenis_jawaban'),
    ]

    operations = [
        migrations.AddField(
            model_name='survei',
            name='sudah_final',
            field=models.BooleanField(default=False),
        ),
    ]
