# Generated by Django 2.1.7 on 2019-04-05 08:03

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinAccount',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Linkedin User Email')),
                ('api_standard_profile_request', models.URLField(help_text="A URL representing the resource you would request for programmatic access to the member's profile.")),
                ('public_profile_url', models.URLField(help_text="The URL to the member's public profile on LinkedIn.")),
                ('user_data', django.contrib.postgres.fields.jsonb.JSONField(help_text='Here is the user linkedin data', verbose_name='Linkedin User Data')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
