# Generated by Django 2.1.7 on 2019-05-16 15:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_auth', '0003_auto_20190405_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinaccount',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Linkedin Email Pengguna'),
        ),
        migrations.AlterField(
            model_name='linkedinaccount',
            name='user_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Berikut adalah data Linkedin pengguna', verbose_name='Linkedin Data Pengguna'),
        ),
    ]
