# Generated by Django 2.1.7 on 2019-09-16 16:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_auth', '0004_auto_20190516_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinaccount',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Linkedin User Email'),
        ),
        migrations.AlterField(
            model_name='linkedinaccount',
            name='user_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Here is the user linkedin data', verbose_name='Linkedin User Data'),
        ),
    ]
