# Generated by Django 2.1.15 on 2023-05-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survei', '0007_pertanyaan_jenis_jawaban'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dikirim', models.DateTimeField(auto_now_add=True)),
                ('group_recipients_years', models.CharField(max_length=500)),
                ('group_recipients_terms', models.CharField(max_length=500)),
                ('individual_recipients_emails', models.CharField(max_length=1200)),
                ('survei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survei.Survei')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('email_subject', models.CharField(max_length=150)),
                ('email_body', models.TextField()),
            ],
        ),
    ]
