# Generated by Django 2.1.15 on 2023-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_blaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecipient',
            name='csv_emails',
            field=models.CharField(default='', max_length=1200),
            preserve_default=False,
        ),
    ]
