# Generated by Django 2.1.7 on 2020-01-07 06:44

import atlas.libs.core.validators
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('ui_sso_npm', models.CharField(blank=True, db_index=True, max_length=16, null=True, validators=[atlas.libs.core.validators.NumericRegex()], verbose_name='SSO UI NPM')),
                ('csui_class_year', models.SmallIntegerField(verbose_name='Angkatan')),
                ('csui_program', models.CharField(blank=True, choices=[('S1-IK', 'S1 - Ilmu Komputer'), ('S1_KI-IK', 'S1 KI - Ilmu Komputer'), ('S1-SI', 'S1 - Sistem Informasi'), ('S1_EKS-SI', 'S1 Ekstensi - Sistem Informasi'), ('S2-IK', 'S2 - Ilmu Komputer'), ('S2-TI', 'S2 - Teknologi Informasi'), ('S3-IK', 'S3 - Ilmu Komputer')], max_length=10, verbose_name='Prodi')),
                ('csui_graduation_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='Kelulusan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('company_name', models.CharField(max_length=64, verbose_name='Company')),
                ('location_name', models.CharField(max_length=64, null=True, verbose_name='Location')),
                ('industry_name', models.CharField(max_length=64, verbose_name='Industry')),
                ('date_started', models.DateField(verbose_name='Date Started')),
                ('date_ended', models.DateField(blank=True, null=True, verbose_name='Date Ended')),
                ('company_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Here is company metadata comes from linkedin', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
