# Generated by Django 2.1.7 on 2019-03-05 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('field_of_study', models.CharField(max_length=64, verbose_name='Field of Study')),
                ('school_name', models.CharField(max_length=64, verbose_name='School')),
                ('degree_name', models.CharField(max_length=64, verbose_name='Degree')),
                ('location_name', models.CharField(max_length=64, verbose_name='Location')),
                ('date_started', models.DateField(verbose_name='Date Started')),
                ('date_ended', models.DateField(blank=True, null=True, verbose_name='Date Ended')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('company_name', models.CharField(max_length=64, verbose_name='Company')),
                ('description', models.TextField(max_length=64, verbose_name='Description')),
                ('location_name', models.CharField(max_length=64, verbose_name='Location')),
                ('industry_name', models.CharField(max_length=64, verbose_name='Industry')),
                ('date_started', models.DateField(verbose_name='Date Started')),
                ('date_ended', models.DateField(blank=True, null=True, verbose_name='Date Ended')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
