# Generated by Django 2.1.7 on 2020-01-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Designates that if this education is not verified,then can't access other services except Account Service", verbose_name='Verified status'),
        ),
    ]
