# Generated by Django 2.1.7 on 2019-03-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_ended',
            field=models.DateField(verbose_name='Date Ended'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
