# Generated by Django 2.1.7 on 2019-03-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_education_date_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='owner',
            new_name='user',
        ),
    ]
