# Generated by Django 2.1.7 on 2022-03-23 17:44

import atlas.libs.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_education_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='csui_graduation_term',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Term Lulus'),
        ),
        migrations.AddField(
            model_name='education',
            name='csui_graduation_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Tahun Lulus'),
        ),
    ]
