# Generated by Django 2.1.7 on 2019-04-05 12:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_rename_owner_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='company_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Here is company metadata comes from linkedin', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='location_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Location'),
        ),
    ]
