# Generated by Django 2.1.7 on 2022-03-27 16:57

import atlas.libs.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experience', '0003_add_field_graduation_year_and_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Negara')),
                ('university', models.CharField(blank=True, max_length=255, null=True, verbose_name='Universitas')),
                ('program', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prodi')),
                ('degree', models.CharField(blank=True, choices=[('S1', 'Sarjana'), ('S2', 'Magister'), ('S3', 'Doktor')], max_length=2, null=True, verbose_name='Jenjang')),
                ('class_year', models.SmallIntegerField(blank=True, null=True, verbose_name='Angkatan')),
                ('is_graduated', models.BooleanField(default=False, verbose_name='Status')),
                ('graduation_year', models.SmallIntegerField(blank=True, null=True, verbose_name='Tahun Lulus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='ui_sso_npm',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, validators=[atlas.libs.core.validators.NpmRegex()], verbose_name='SSO UI NPM'),
        ),
    ]
