# Generated by Django 2.1.7 on 2022-05-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_add_other_education_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='salary_range',
            field=models.CharField(blank=True, choices=[('1', '<= 1.000.000'), ('2', '1.000.001 - 3.000.000'), ('3', '3.000.001 - 6.000.000'), ('4', '6.000.001 - 10.000.000'), ('5', '10.000.001 - 15.000.000'), ('6', '15.000.001 - 20.000.000'), ('7', '> 20.000.000')], max_length=10, null=True, verbose_name='Rentang Gaji'),
        ),
    ]
