# Generated by Django 2.1.7 on 2019-04-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_auto_20190405_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
    ]
