# Generated by Django 2.1.7 on 2019-05-16 15:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_remove_position_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_ended',
            field=models.DateField(verbose_name='Tanggal Selesai'),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_started',
            field=models.DateField(verbose_name='Tanggal Mulai'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_name',
            field=models.CharField(max_length=64, verbose_name='Gelar'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=64, verbose_name='Bidang Studi'),
        ),
        migrations.AlterField(
            model_name='education',
            name='location_name',
            field=models.CharField(max_length=64, verbose_name='Lokasi'),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(max_length=64, verbose_name='Sekolah'),
        ),
        migrations.AlterField(
            model_name='position',
            name='company_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Berikut metadata perusahaan dari Linkedin', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='company_name',
            field=models.CharField(max_length=64, verbose_name='Perusahaan'),
        ),
        migrations.AlterField(
            model_name='position',
            name='date_ended',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai'),
        ),
        migrations.AlterField(
            model_name='position',
            name='date_started',
            field=models.DateField(verbose_name='Tanggal Mulai'),
        ),
        migrations.AlterField(
            model_name='position',
            name='industry_name',
            field=models.CharField(max_length=64, verbose_name='Industri'),
        ),
        migrations.AlterField(
            model_name='position',
            name='location_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Lokasi'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Judul'),
        ),
    ]
