# Generated by Django 2.1.7 on 2022-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_add_salary_range_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_from_sisidang',
            field=models.BooleanField(default=False, verbose_name='From Sisidang'),
        ),
        migrations.AlterField(
            model_name='position',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='position',
            name='location_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
