# Generated by Django 2.1.7 on 2019-09-16 16:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_auto_20190516_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_ended',
            field=models.DateField(verbose_name='Date Ended'),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_started',
            field=models.DateField(verbose_name='Date Started'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_name',
            field=models.CharField(max_length=64, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=64, verbose_name='Field of Study'),
        ),
        migrations.AlterField(
            model_name='education',
            name='location_name',
            field=models.CharField(max_length=64, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(max_length=64, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='position',
            name='company_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Here is company metadata comes from linkedin', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='company_name',
            field=models.CharField(max_length=64, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='position',
            name='date_ended',
            field=models.DateField(blank=True, null=True, verbose_name='Date Ended'),
        ),
        migrations.AlterField(
            model_name='position',
            name='date_started',
            field=models.DateField(verbose_name='Date Started'),
        ),
        migrations.AlterField(
            model_name='position',
            name='industry_name',
            field=models.CharField(max_length=64, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='position',
            name='location_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Title'),
        ),
    ]
