# Generated by Django 2.1.7 on 2022-06-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_adjust_field_for_sisidang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='location_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
    ]
