# Generated by Django 2.1.7 on 2022-05-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_adjust_field_for_sisidang_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
