# Generated by Django 2.1.7 on 2022-05-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0008_change_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_started',
            field=models.DateField(null=True, verbose_name='Date Started'),
        ),
    ]
