# Generated by Django 2.1.7 on 2023-03-25 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survei', '0007_pertanyaan_jenis_jawaban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=1200)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survei.Pertanyaan')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diedit', models.DateTimeField(auto_now=True)),
                ('survei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survei.Survei')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jawaban',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response.Response'),
        ),
    ]
