# Generated by Django 2.1.7 on 2023-03-25 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='tanggal_diedit',
        ),
        migrations.AddField(
            model_name='jawaban',
            name='tanggal_dibuat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
